-- RUN THIS IN: the Supabase project that does NOT yet have the table
--   kr_checkins (snapshot 64afccf0 = "B"). Do not run it in the project
--   that already has kr_checkins / projects.color (snapshot ccb79579 = "A").
-- Run PART 1 as-is. PART 2 is commented out: read it before running any line.
-- ============================================================
--  DELTA: bring schema B up to schema A (generated by
--  scripts/schema_delta.py). Nothing is dropped.
-- ============================================================

-- PART 1 — safe, additive. One transaction: all or nothing.
begin;

create extension if not exists pgcrypto;
create extension if not exists "uuid-ossp";

-- table Goals
create table if not exists public."Goals" (
    "goal_ed" date,
    "goal_id" bigint,
    "goal_sd" date,
    "goal_name" text,
    "goal_owner" text,
    "goal_status" text,
    "goal_completion" bigint,
    "goal_description" text
);
-- table prep_notes
create table if not exists public."prep_notes" (
    "id" uuid default gen_random_uuid() not null,
    "bank" text not null,
    "note" text default ''::text not null,
    "user_id" text not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "entry_title" text not null,
    constraint "prep_notes_pkey" PRIMARY KEY (id)
);
-- table daily_tasks
create sequence if not exists daily_tasks_id_seq;
create table if not exists public."daily_tasks" (
    "id" integer default nextval('daily_tasks_id_seq'::regclass) not null,
    "slot" integer not null,
    "task" text,
    "task_date" date,
    "task_status" text,
    constraint "slot_range" CHECK (((slot >= 1) AND (slot <= 48))),
    constraint "daily_tasks_pkey" PRIMARY KEY (id),
    constraint "daily_tasks_date_slot_unique" UNIQUE (task_date, slot)
);
-- table investments
create table if not exists public."investments" (
    "id" uuid default gen_random_uuid() not null,
    "name" text not null,
    "type" text,
    "amount" numeric(14,2) default 0 not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    "invested_on" date default CURRENT_DATE not null,
    constraint "investments_pkey" PRIMARY KEY (id),
    constraint "investments_amount_check" CHECK ((amount >= (0)::numeric))
);
-- table kr_checkins
create table if not exists public."kr_checkins" (
    "id" uuid default gen_random_uuid() not null,
    "note" text,
    "value" numeric not null,
    "user_id" text not null,
    "created_at" timestamp with time zone default now(),
    "objective_id" uuid,
    "key_result_id" uuid not null,
    "previous_value" numeric,
    constraint "kr_checkins_pkey" PRIMARY KEY (id)
);
-- table login_events
create table if not exists public."login_events" (
    "at" timestamp with time zone default now() not null,
    "id" uuid default gen_random_uuid() not null,
    "ip" text,
    "city" text,
    "region" text,
    "country" text,
    "outcome" text default 'success'::text not null,
    "user_id" text not null,
    "timezone" text,
    "created_at" timestamp with time zone default now() not null,
    "user_agent" text,
    "country_code" text,
    "location_status" text default 'pending'::text not null,
    constraint "login_events_pkey" PRIMARY KEY (id)
);
-- table shared_items
create table if not exists public."shared_items" (
    "id" uuid default gen_random_uuid() not null,
    "bank" text,
    "kind" text not null,
    "due_date" date,
    "due_time" time without time zone,
    "item_ref" text not null,
    "item_url" text,
    "owner_id" text not null,
    "created_at" timestamp with time zone default now(),
    "item_title" text,
    "shared_with" text not null,
    "completed_at" timestamp with time zone,
    constraint "shared_items_pkey" PRIMARY KEY (id)
);
-- table daily_summary
create table if not exists public."daily_summary" (
    "habits" text,
    "plan_date" date not null,
    "reflection" text,
    constraint "daily_summary_pkey" PRIMARY KEY (plan_date)
);
-- table day_board_pins
create table if not exists public."day_board_pins" (
    "user_id" text not null,
    "end_hour" smallint default 22 not null,
    "is_active" boolean default false not null,
    "created_at" timestamp with time zone default now() not null,
    "start_hour" smallint default 7 not null,
    "updated_at" timestamp with time zone default now() not null,
    "pinned_date" date,
    "last_sent_at" timestamp with time zone,
    "last_signature" text,
    "min_interval_minutes" smallint default 10 not null,
    constraint "day_board_pins_pkey" PRIMARY KEY (user_id),
    constraint "day_board_pins_hours_ck" CHECK ((((start_hour >= 0) AND (start_hour <= 23)) AND ((end_hour >= 0) AND (end_hour <= 23)) AND ((min_interval_minutes >= 1) AND (min_interval_minutes <= 240))))
);
-- table interview_prep
create table if not exists public."interview_prep" (
    "id" uuid default gen_random_uuid() not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "role_title" text default 'Senior Director, Technical Program Management'::text not null,
    "updated_at" timestamp with time zone default now() not null,
    "target_date" date,
    "daily_goal_minutes" integer default 45 not null,
    constraint "interview_prep_pkey" PRIMARY KEY (id),
    constraint "interview_prep_user_id_key" UNIQUE (user_id),
    constraint "interview_prep_daily_goal_minutes_check" CHECK ((daily_goal_minutes >= 0))
);
-- table ai_sde_progress
create table if not exists public."ai_sde_progress" (
    "id" uuid default gen_random_uuid() not null,
    "studied" boolean default false not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "is_deleted" boolean default false not null,
    "review_due" timestamp with time zone,
    "studied_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    "entry_title" text not null,
    "review_last" timestamp with time zone,
    "quiz_correct" integer default 0 not null,
    "quiz_attempts" integer default 0 not null,
    "review_streak" integer default 0 not null,
    "minutes_focused" integer default 0 not null,
    constraint "ai_sde_progress_pkey" PRIMARY KEY (id)
);
-- table announcer_items
create table if not exists public."announcer_items" (
    "id" uuid default gen_random_uuid() not null,
    "days" integer[] default '{}'::integer[] not null,
    "is_on" boolean default true not null,
    "notify" boolean default true not null,
    "at_time" text not null,
    "user_id" text not null,
    "end_date" date,
    "say_text" text default ''::text not null,
    "client_id" text not null,
    "created_at" timestamp with time zone default now() not null,
    "every_mins" integer default 0 not null,
    "is_deleted" boolean default false not null,
    "start_date" date,
    "until_time" text,
    "updated_at" timestamp with time zone default now() not null,
    "repeat_rule" text default 'daily'::text not null,
    "google_event_id" text,
    constraint "announcer_items_pkey" PRIMARY KEY (id)
);
-- table recurring_slots
create table if not exists public."recurring_slots" (
    "id" uuid default gen_random_uuid() not null,
    "title" text not null,
    "user_id" text not null,
    "end_date" date,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "slot_count" integer not null,
    "start_date" date not null,
    "start_slot" integer not null,
    "days_of_week" integer[],
    "interval_value" integer,
    "recurrence_type" text not null,
    constraint "recurring_slots_pkey" PRIMARY KEY (id)
);
-- table daily_reflection
create table if not exists public."daily_reflection" (
    "user_id" text not null,
    "plan_date" date not null,
    "reflection" text,
    constraint "daily_reflection_pkey" PRIMARY KEY (user_id, plan_date)
);
-- table eisenhower_notes
create table if not exists public."eisenhower_notes" (
    "id" bigint not null,
    "notes" text not null,
    "plan_date" date not null,
    "created_at" timestamp with time zone default now(),
    constraint "eisenhower_notes_pkey" PRIMARY KEY (id),
    constraint "eisenhower_notes_plan_date_key" UNIQUE (plan_date)
);
-- table interview_topics
create table if not exists public."interview_topics" (
    "id" uuid default gen_random_uuid() not null,
    "notes" text,
    "title" text not null,
    "user_id" uuid not null,
    "category" text default 'domain'::text not null,
    "position" integer default 0 not null,
    "confidence" smallint default 0 not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    constraint "interview_topics_pkey" PRIMARY KEY (id),
    constraint "interview_topics_confidence_check" CHECK (((confidence >= 0) AND (confidence <= 4)))
);
-- table interview_stories
create table if not exists public."interview_stories" (
    "id" uuid default gen_random_uuid() not null,
    "task" text,
    "title" text not null,
    "action" text,
    "result" text,
    "user_id" uuid not null,
    "position" integer default 0 not null,
    "rehearsed" boolean default false not null,
    "situation" text,
    "competency" text,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    constraint "interview_stories_pkey" PRIMARY KEY (id)
);
-- table announcer_fire_log
create table if not exists public."announcer_fire_log" (
    "id" uuid default gen_random_uuid() not null,
    "sent" integer,
    "failed" integer,
    "user_id" text not null,
    "client_id" text not null,
    "fire_date" date not null,
    "fire_time" text not null,
    "created_at" timestamp with time zone default now() not null,
    constraint "announcer_fire_log_pkey" PRIMARY KEY (id)
);
-- table announcer_settings
create table if not exists public."announcer_settings" (
    "label" text default ''::text not null,
    "user_id" text not null,
    "every_mins" integer default 15 not null,
    "updated_at" timestamp with time zone default now() not null,
    constraint "announcer_settings_pkey" PRIMARY KEY (user_id)
);
-- table interview_sessions
create table if not exists public."interview_sessions" (
    "id" uuid default gen_random_uuid() not null,
    "focus" text,
    "minutes" integer default 0 not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "reflection" text,
    "practiced_on" date default CURRENT_DATE not null,
    constraint "interview_sessions_pkey" PRIMARY KEY (id),
    constraint "interview_sessions_minutes_check" CHECK ((minutes >= 0))
);
-- table objective_references
create table if not exists public."objective_references" (
    "id" uuid default gen_random_uuid() not null,
    "url" text not null,
    "kind" text default 'link'::text,
    "title" text not null,
    "user_id" text not null,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "is_deleted" boolean default false not null,
    "description" text,
    "order_index" integer default 0 not null,
    "objective_id" uuid not null,
    constraint "objective_references_pkey" PRIMARY KEY (id)
);
-- table health_daily_archived
create table if not exists public."health_daily_archived" (
    "id" uuid default gen_random_uuid() not null,
    "mood" text,
    "notes" text,
    "weight" numeric(5,2),
    "user_id" uuid not null,
    "plan_date" date not null,
    "created_at" timestamp without time zone default now(),
    "sleep_hours" numeric(4,2),
    "energy_level" integer,
    constraint "health_daily_pkey" PRIMARY KEY (id),
    constraint "health_daily_user_id_plan_date_key" UNIQUE (user_id, plan_date)
);
-- table eisenhower_notes_tasks
create table if not exists public."eisenhower_notes_tasks" (
    "id" bigint not null,
    "is_done" boolean default false,
    "position" integer default 0,
    "plan_date" date not null,
    "task_text" text not null,
    "created_at" timestamp with time zone default now(),
    constraint "eisenhower_notes_tasks_pkey" PRIMARY KEY (id)
);
-- table system_design_overrides
create table if not exists public."system_design_overrides" (
    "id" uuid default gen_random_uuid() not null,
    "arch" text,
    "title" text,
    "answer" text,
    "example" text,
    "problem" text,
    "user_id" uuid not null,
    "entry_id" text not null,
    "competing" text,
    "use_cases" text,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    "disadvantages" text,
    constraint "system_design_overrides_pkey" PRIMARY KEY (id),
    constraint "system_design_overrides_user_id_entry_id_key" UNIQUE (user_id, entry_id)
);
-- table interview_question_overrides
create table if not exists public."interview_question_overrides" (
    "id" uuid default gen_random_uuid() not null,
    "tip" text,
    "task" text,
    "action" text,
    "result" text,
    "user_id" uuid not null,
    "question" text,
    "situation" text,
    "created_at" timestamp with time zone default now() not null,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null,
    "question_id" text not null,
    constraint "interview_question_overrides_pkey" PRIMARY KEY (id),
    constraint "interview_question_overrides_user_id_question_id_key" UNIQUE (user_id, question_id)
);
alter table public."tags" alter column "name" drop not null;
alter table public."tags" alter column "user_id" drop not null;
alter table public."tags" add column if not exists "created_at" timestamp without time zone default now();
alter table public."expenses" add column if not exists "tag" text;
alter table public."expenses" add column if not exists "cost_type" text;
alter table public."expenses" add column if not exists "need_want" text;
alter table public."expenses" add column if not exists "recurrence" text default 'none'::text not null;
alter table public."projects" add column if not exists "color" text;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'projects_color_is_hex' and conrelid = 'public."projects"'::regclass) then
    alter table public."projects" add constraint "projects_color_is_hex" CHECK (((color IS NULL) OR (color ~ '^#[0-9a-fA-F]{6}$'::text))) NOT VALID;
  end if;
end $$;
alter table public."daily_meta" add column if not exists "mood" text;
alter table public."daily_meta" alter column "habits" set default '[]'::jsonb;
alter table public."daily_meta" add column if not exists "weight" numeric;
alter table public."daily_meta" alter column "reflection" set default ''::text;
alter table public."daily_meta" add column if not exists "updated_at" timestamp with time zone default now();
alter table public."daily_meta" add column if not exists "sleep_hours" numeric;
alter table public."daily_meta" alter column "untimed_tasks" set default '[]'::jsonb;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'daily_meta_pkey' and conrelid = 'public."daily_meta"'::regclass) then
    alter table public."daily_meta" add constraint "daily_meta_pkey" PRIMARY KEY (user_id, plan_date);
  end if;
end $$;
alter table public."objectives" add column if not exists "target_at" timestamp with time zone;
alter table public."objectives" add column if not exists "is_primary" boolean default false;
alter table public."objectives" add column if not exists "flash_enabled" boolean default true;
alter table public."objectives" add column if not exists "effort_minutes" integer;
alter table public."objectives" add column if not exists "manual_progress" integer;
alter table public."objectives" add column if not exists "daily_commit_minutes" integer;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'objectives_manual_progress_range' and conrelid = 'public."objectives"'::regclass) then
    alter table public."objectives" add constraint "objectives_manual_progress_range" CHECK (((manual_progress IS NULL) OR ((manual_progress >= 0) AND (manual_progress <= 100))));
  end if;
end $$;
alter table public."daily_slots" alter column "user_id" drop not null;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'daily_slots_pkey' and conrelid = 'public."daily_slots"'::regclass) then
    alter table public."daily_slots" add constraint "daily_slots_pkey" PRIMARY KEY (plan_date, slot);
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'daily_slots_unique' and conrelid = 'public."daily_slots"'::regclass) then
    alter table public."daily_slots" add constraint "daily_slots_unique" UNIQUE (user_id, plan_date, slot);
  end if;
end $$;
alter table public."inbox_links" alter column "id" set default gen_random_uuid();
alter table public."inbox_links" alter column "category" set default 'Uncategorized'::text;
alter table public."key_results" add column if not exists "due_at" timestamp with time zone;
alter table public."key_results" add column if not exists "last_checked_at" timestamp with time zone;
alter table public."todo_matrix" add column if not exists "notes" text;
alter table public."todo_matrix" alter column "user_id" drop not null;
alter table public."todo_matrix" add column if not exists "travel_mode" boolean default false;
alter table public."todo_matrix" add column if not exists "recurring_instance_id" uuid;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'todo_matrix_quadrant_check' and conrelid = 'public."todo_matrix"'::regclass) then
    alter table public."todo_matrix" add constraint "todo_matrix_quadrant_check" CHECK ((quadrant = ANY (ARRAY['do'::text, 'schedule'::text, 'delegate'::text, 'eliminate'::text])));
  end if;
end $$;
alter table public."daily_events" alter column "id" set default uuid_generate_v4();
alter table public."daily_events" alter column "status" set default 'open'::text;
alter table public."daily_events" add column if not exists "updated_at" timestamp without time zone default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'unique_google_event_id' and conrelid = 'public."daily_events"'::regclass) then
    alter table public."daily_events" add constraint "unique_google_event_id" UNIQUE (google_event_id);
  end if;
end $$;
alter table public."daily_health" add column if not exists "created_at" timestamp with time zone default now();
alter table public."daily_health" add column if not exists "updated_at" timestamp with time zone default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'daily_health_pkey' and conrelid = 'public."daily_health"'::regclass) then
    alter table public."daily_health" add constraint "daily_health_pkey" PRIMARY KEY (user_id, plan_date);
  end if;
end $$;
alter table public."habit_master" alter column "goal" set default 0;
alter table public."habit_master" alter column "position" set default 0;
alter table public."habit_master" alter column "habit_type" set default 'numeric'::text;
alter table public."habit_master" alter column "start_date" set default CURRENT_DATE;
alter table public."quick_bucket" add column if not exists "backlog_due" date;
alter table public."quick_bucket" add column if not exists "effort_date" date;
alter table public."quick_bucket" add column if not exists "scheduled_for" date;
alter table public."quick_bucket" add column if not exists "actual_minutes" integer;
alter table public."quick_bucket" add column if not exists "source_task_id" uuid;
alter table public."quick_bucket" add column if not exists "google_event_id" text;
alter table public."quick_bucket" add column if not exists "planned_minutes" integer;
alter table public."quick_bucket" add column if not exists "scheduled_event_id" text;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'quick_bucket_actual_minutes_chk' and conrelid = 'public."quick_bucket"'::regclass) then
    alter table public."quick_bucket" add constraint "quick_bucket_actual_minutes_chk" CHECK (((actual_minutes IS NULL) OR (actual_minutes >= 0)));
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'quick_bucket_planned_minutes_chk' and conrelid = 'public."quick_bucket"'::regclass) then
    alter table public."quick_bucket" add constraint "quick_bucket_planned_minutes_chk" CHECK (((planned_minutes IS NULL) OR (planned_minutes >= 0)));
  end if;
end $$;
alter table public."travel_tasks" alter column "category" set default 'Default'::text;
alter table public."travel_tasks" alter column "subcategory" set default 'General'::text;
alter table public."habit_entries" add column if not exists "created_at" timestamp without time zone default now();
alter table public."project_tasks" alter column "user_id" drop not null;
alter table public."project_tasks" add column if not exists "end_time" time without time zone;
alter table public."project_tasks" alter column "priority" set default 'high'::text;
alter table public."project_tasks" add column if not exists "recurrence" text;
alter table public."project_tasks" alter column "order_index" drop default;
alter table public."project_tasks" alter column "actual_hours" set default 0;
alter table public."project_tasks" add column if not exists "objective_id" uuid;
alter table public."project_tasks" alter column "planned_hours" set default 0;
alter table public."project_tasks" alter column "priority_rank" drop default;
alter table public."project_tasks" alter column "recurrence_type" set default 'none'::text;
alter table public."project_tasks" add column if not exists "sent_to_eisenhower" boolean default false;
alter table public."project_tasks" add column if not exists "planning_updated_at" timestamp with time zone;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'hours_non_negative' and conrelid = 'public."project_tasks"'::regclass) then
    alter table public."project_tasks" add constraint "hours_non_negative" CHECK (((planned_hours >= (0)::numeric) AND (actual_hours >= (0)::numeric)));
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'duration_days_non_negative' and conrelid = 'public."project_tasks"'::regclass) then
    alter table public."project_tasks" add constraint "duration_days_non_negative" CHECK ((duration_days >= 0));
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'project_tasks_priority_check' and conrelid = 'public."project_tasks"'::regclass) then
    alter table public."project_tasks" add constraint "project_tasks_priority_check" CHECK ((priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])));
  end if;
end $$;
alter table public."scribble_notes" add column if not exists "tags" text[];
alter table public."scribble_notes" add column if not exists "created_at" timestamp with time zone default now();
alter table public."scribble_notes" add column if not exists "is_archived" boolean default false;
alter table public."scribble_notes" add column if not exists "content_type" text default 'markdown'::text;
alter table public."scribble_notes" add column if not exists "linked_task_id" uuid;
alter table public."task_overrides" add column if not exists "id" uuid default gen_random_uuid() not null;
alter table public."task_overrides" add column if not exists "title" text;
alter table public."task_overrides" add column if not exists "updated_at" timestamp with time zone default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'task_overrides_pkey' and conrelid = 'public."task_overrides"'::regclass) then
    alter table public."task_overrides" add constraint "task_overrides_pkey" PRIMARY KEY (id);
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'task_overrides_task_id_task_date_key' and conrelid = 'public."task_overrides"'::regclass) then
    alter table public."task_overrides" add constraint "task_overrides_task_id_task_date_key" UNIQUE (task_id, task_date);
  end if;
end $$;
alter table public."checklist_items" add column if not exists "notify_muted" boolean default false not null;
alter table public."recurring_tasks" alter column "user_id" drop not null;
alter table public."recurring_tasks" add column if not exists "created_at" timestamp without time zone default now();
alter table public."event_exceptions" alter column "reason" drop default;
alter table public."project_subtasks" add column if not exists "deleted_at" timestamp with time zone;
alter table public."project_subtasks" add column if not exists "is_deleted" boolean default false;

-- FUNCTIONS (needed by triggers below)
-- day_board_pins_touch()  (from MIGRATION_DAY_BOARD_PIN.sql)
create or replace function day_board_pins_touch()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- FOREIGN KEYS (after every table exists)
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'investments_user_id_fkey' and conrelid = 'public."investments"'::regclass) then
    alter table public."investments" add constraint "investments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'kr_checkins_objective_id_fkey' and conrelid = 'public."kr_checkins"'::regclass) then
    alter table public."kr_checkins" add constraint "kr_checkins_objective_id_fkey" FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'kr_checkins_key_result_id_fkey' and conrelid = 'public."kr_checkins"'::regclass) then
    alter table public."kr_checkins" add constraint "kr_checkins_key_result_id_fkey" FOREIGN KEY (key_result_id) REFERENCES key_results(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'interview_prep_user_id_fkey' and conrelid = 'public."interview_prep"'::regclass) then
    alter table public."interview_prep" add constraint "interview_prep_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'interview_topics_user_id_fkey' and conrelid = 'public."interview_topics"'::regclass) then
    alter table public."interview_topics" add constraint "interview_topics_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'interview_stories_user_id_fkey' and conrelid = 'public."interview_stories"'::regclass) then
    alter table public."interview_stories" add constraint "interview_stories_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'interview_sessions_user_id_fkey' and conrelid = 'public."interview_sessions"'::regclass) then
    alter table public."interview_sessions" add constraint "interview_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'objective_references_objective_id_fkey' and conrelid = 'public."objective_references"'::regclass) then
    alter table public."objective_references" add constraint "objective_references_objective_id_fkey" FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'system_design_overrides_user_id_fkey' and conrelid = 'public."system_design_overrides"'::regclass) then
    alter table public."system_design_overrides" add constraint "system_design_overrides_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'interview_question_overrides_user_id_fkey' and conrelid = 'public."interview_question_overrides"'::regclass) then
    alter table public."interview_question_overrides" add constraint "interview_question_overrides_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'fk_todo_project' and conrelid = 'public."todo_matrix"'::regclass) then
    alter table public."todo_matrix" add constraint "fk_todo_project" FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE SET NULL;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'project_tasks_key_result_id_fkey' and conrelid = 'public."project_tasks"'::regclass) then
    alter table public."project_tasks" add constraint "project_tasks_key_result_id_fkey" FOREIGN KEY (key_result_id) REFERENCES key_results(id) ON DELETE SET NULL;
  end if;
end $$;

-- INDEXES AND TRIGGERS
CREATE INDEX IF NOT EXISTS prep_notes_user_bank_idx ON public.prep_notes USING btree (user_id, bank);
CREATE UNIQUE INDEX IF NOT EXISTS prep_notes_user_bank_title_idx ON public.prep_notes USING btree (user_id, bank, entry_title);
CREATE INDEX IF NOT EXISTS investments_user_idx ON public.investments USING btree (user_id, invested_on DESC) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS ix_kr_checkins_kr_created ON public.kr_checkins USING btree (key_result_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_kr_checkins_user_created ON public.kr_checkins USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS login_events_user_at_idx ON public.login_events USING btree (user_id, at DESC);
CREATE INDEX IF NOT EXISTS shared_items_owner_idx ON public.shared_items USING btree (owner_id, kind, item_ref);
CREATE INDEX IF NOT EXISTS shared_items_recipient_idx ON public.shared_items USING btree (shared_with, due_date);
CREATE UNIQUE INDEX IF NOT EXISTS shared_items_unique_grant_idx ON public.shared_items USING btree (kind, item_ref, shared_with);
CREATE INDEX IF NOT EXISTS day_board_pins_active_idx ON public.day_board_pins USING btree (is_active) WHERE is_active;
-- trigger day_board_pins_touch_trg (needs its function — see FUNCTIONS below)
drop trigger if exists "day_board_pins_touch_trg" on public."day_board_pins";
CREATE TRIGGER day_board_pins_touch_trg BEFORE UPDATE ON public.day_board_pins FOR EACH ROW EXECUTE FUNCTION day_board_pins_touch();
CREATE INDEX IF NOT EXISTS ai_sde_progress_due_idx ON public.ai_sde_progress USING btree (user_id, review_due) WHERE ((review_due IS NOT NULL) AND (NOT is_deleted));
CREATE INDEX IF NOT EXISTS ai_sde_progress_user_idx ON public.ai_sde_progress USING btree (user_id) WHERE (NOT is_deleted);
CREATE UNIQUE INDEX IF NOT EXISTS ai_sde_progress_user_title ON public.ai_sde_progress USING btree (user_id, entry_title);
CREATE INDEX IF NOT EXISTS announcer_items_user_live_idx ON public.announcer_items USING btree (user_id) WHERE (is_deleted = false);
CREATE UNIQUE INDEX IF NOT EXISTS announcer_items_user_client_idx ON public.announcer_items USING btree (user_id, client_id);
CREATE INDEX IF NOT EXISTS interview_topics_user_idx ON public.interview_topics USING btree (user_id, category, "position") WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS interview_stories_user_idx ON public.interview_stories USING btree (user_id, "position", created_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS announcer_fire_log_date_idx ON public.announcer_fire_log USING btree (fire_date);
CREATE UNIQUE INDEX IF NOT EXISTS announcer_fire_log_claim_idx ON public.announcer_fire_log USING btree (user_id, client_id, fire_date, fire_time);
CREATE INDEX IF NOT EXISTS interview_sessions_user_idx ON public.interview_sessions USING btree (user_id, practiced_on DESC) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS obj_refs_objective_idx ON public.objective_references USING btree (objective_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS eisenhower_notes_tasks_plan_date_idx ON public.eisenhower_notes_tasks USING btree (plan_date);
CREATE INDEX IF NOT EXISTS system_design_override_user_idx ON public.system_design_overrides USING btree (user_id) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS interview_qoverride_user_idx ON public.interview_question_overrides USING btree (user_id) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_projects_user_active ON public.projects USING btree (user_id, is_archived);
CREATE UNIQUE INDEX IF NOT EXISTS projects_one_javaprep_per_user ON public.projects USING btree (user_id) WHERE ((name = 'JavaPrep'::text) AND (is_archived = false));
CREATE UNIQUE INDEX IF NOT EXISTS projects_one_aisdeprep_per_user ON public.projects USING btree (user_id) WHERE ((name = 'AISDEPrep'::text) AND (is_archived = false));
CREATE UNIQUE INDEX IF NOT EXISTS projects_one_interviewprep_per_user ON public.projects USING btree (user_id) WHERE ((name = 'InterviewPrep'::text) AND (is_archived = false));
CREATE INDEX IF NOT EXISTS idx_ref_cards_context ON public.ref_cards USING btree (property_id);
-- objectives_user_idx: B had CREATE INDEX objectives_user_idx ON public.objectives USING btree (user_id, status)
drop index if exists public."objectives_user_idx";
CREATE INDEX IF NOT EXISTS objectives_user_idx ON public.objectives USING btree (user_id, status) WHERE (is_deleted = false);
-- objectives_project_idx: B had CREATE INDEX objectives_project_idx ON public.objectives USING btree (project_id)
drop index if exists public."objectives_project_idx";
CREATE INDEX IF NOT EXISTS objectives_project_idx ON public.objectives USING btree (project_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS objectives_target_at_idx ON public.objectives USING btree (user_id, target_at) WHERE (NOT is_deleted);
CREATE UNIQUE INDEX IF NOT EXISTS objectives_one_primary_per_user ON public.objectives USING btree (user_id) WHERE (is_primary AND (NOT is_deleted));
-- initiatives_kr_idx: B had CREATE INDEX initiatives_kr_idx ON public.initiatives USING btree (key_result_id)
drop index if exists public."initiatives_kr_idx";
CREATE INDEX IF NOT EXISTS initiatives_kr_idx ON public.initiatives USING btree (key_result_id) WHERE (is_deleted = false);
-- kr_objective_idx: B had CREATE INDEX kr_objective_idx ON public.key_results USING btree (objective_id)
drop index if exists public."kr_objective_idx";
CREATE INDEX IF NOT EXISTS kr_objective_idx ON public.key_results USING btree (objective_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_todo_matrix_date ON public.todo_matrix USING btree (plan_date);
CREATE INDEX IF NOT EXISTS todo_matrix_project_id_idx ON public.todo_matrix USING btree (project_id);
CREATE INDEX IF NOT EXISTS idx_todo_matrix_source_task_id ON public.todo_matrix USING btree (source_task_id);
CREATE INDEX IF NOT EXISTS todo_matrix_user_id_plan_date_idx ON public.todo_matrix USING btree (user_id, plan_date);
CREATE INDEX IF NOT EXISTS idx_events_time ON public.daily_events USING btree (plan_date, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_daily_events_google_id ON public.daily_events USING btree (google_event_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_habit_name ON public.habit_master USING btree (user_id, lower(name)) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS quick_bucket_scheduled_idx ON public.quick_bucket USING btree (user_id, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_quick_bucket_backlog_due ON public.quick_bucket USING btree (user_id, backlog_due) WHERE (backlog_due IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_quick_bucket_source_task ON public.quick_bucket USING btree (source_task_id) WHERE (source_task_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS quick_bucket_user_effort_idx ON public.quick_bucket USING btree (user_id, effort_date) WHERE ((effort_date IS NOT NULL) AND (is_deleted = false));
CREATE INDEX IF NOT EXISTS travel_tasks_user_cat_idx ON public.travel_tasks USING btree (user_id, category);
CREATE INDEX IF NOT EXISTS idx_habit_entries_date ON public.habit_entries USING btree (user_id, plan_date);
-- project_tasks_revised_idx: B had CREATE INDEX project_tasks_revised_idx ON public.project_tasks USING btree (user_id, revised_due_date) WHERE ((is_deleted = false) AND (is_eliminated = false))
drop index if exists public."project_tasks_revised_idx";
CREATE INDEX IF NOT EXISTS project_tasks_revised_idx ON public.project_tasks USING btree (user_id, revised_due_date) WHERE (is_eliminated = false);
CREATE INDEX IF NOT EXISTS idx_project_tasks_plan_date ON public.project_tasks USING btree (plan_date);
CREATE INDEX IF NOT EXISTS project_tasks_objective_idx ON public.project_tasks USING btree (objective_id) WHERE (objective_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS project_tasks_project_plan_date_idx ON public.project_tasks USING btree (project_id, plan_date) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_task_overrides_lookup ON public.task_overrides USING btree (task_id, task_date);
CREATE INDEX IF NOT EXISTS checklist_items_notify_live_idx ON public.checklist_items USING btree (user_id) WHERE ((is_deleted = false) AND (notify_muted = false));
CREATE INDEX IF NOT EXISTS recurring_tasks_user_idx ON public.recurring_tasks USING btree (user_id) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_reference_tags ON public.reference_links USING gin (tags);
CREATE INDEX IF NOT EXISTS idx_reference_user ON public.reference_links USING btree (user_id);
CREATE INDEX IF NOT EXISTS project_subtasks_id_idx ON public.project_subtasks USING btree (id);
CREATE INDEX IF NOT EXISTS idx_ref_activity_log_card ON public.ref_activity_log USING btree (bill_id);
CREATE INDEX IF NOT EXISTS idx_habit_goal_lookup ON public.habit_goal_history USING btree (habit_id, effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_portfolio_txn_user ON public.portfolio_transactions USING btree (user_id);

commit;


-- PART 2 — REVIEW BEFORE RUNNING. Commented out on purpose: these
-- rewrite columns or can fail on existing rows.
-- tags.id: A=uuid  B=integer
-- alter table public."tags" alter column "id" type uuid using "id"::uuid;
-- projects.created_at: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."projects" alter column "created_at" set not null;
-- projects.is_archived: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."projects" alter column "is_archived" set not null;
-- objectives.status: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."objectives" alter column "status" set not null;
-- objectives.user_id: A=text  B=uuid
-- alter table public."objectives" alter column "user_id" type text using "user_id"::text;
-- objectives.created_at: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."objectives" alter column "created_at" set not null;
-- objectives.is_deleted: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."objectives" alter column "is_deleted" set not null;
-- objectives.order_index: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."objectives" alter column "order_index" set not null;
-- inbox_links.url: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."inbox_links" alter column "url" set not null;
-- inbox_links.created_at: A=timestamp without time zone  B=timestamp with time zone
-- alter table public."inbox_links" alter column "created_at" type timestamp without time zone using "created_at"::timestamp without time zone;
-- inbox_links.reminder_at: A=timestamp without time zone  B=timestamp with time zone
-- alter table public."inbox_links" alter column "reminder_at" type timestamp without time zone using "reminder_at"::timestamp without time zone;
-- initiatives.status: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."initiatives" alter column "status" set not null;
-- initiatives.user_id: A=text  B=uuid
-- alter table public."initiatives" alter column "user_id" type text using "user_id"::text;
-- initiatives.created_at: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."initiatives" alter column "created_at" set not null;
-- initiatives.is_deleted: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."initiatives" alter column "is_deleted" set not null;
-- initiatives.order_index: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."initiatives" alter column "order_index" set not null;
-- key_results.user_id: A=text  B=uuid
-- alter table public."key_results" alter column "user_id" type text using "user_id"::text;
-- key_results.direction: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "direction" set not null;
-- key_results.created_at: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "created_at" set not null;
-- key_results.is_deleted: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "is_deleted" set not null;
-- key_results.order_index: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "order_index" set not null;
-- key_results.start_value: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "start_value" set not null;
-- key_results.current_value: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "current_value" set not null;
-- key_results.progress_source: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."key_results" alter column "progress_source" set not null;
-- todo_matrix.task_time: A=time without time zone  B=text
-- alter table public."todo_matrix" alter column "task_time" type time without time zone using "task_time"::time without time zone;
-- daily_events.title: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."daily_events" alter column "title" set not null;
-- daily_events.end_time: A=time without time zone  B=text
-- alter table public."daily_events" alter column "end_time" type time without time zone using "end_time"::time without time zone;
-- daily_events.end_time: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."daily_events" alter column "end_time" set not null;
-- daily_events.priority: A=character varying(10)  B=text
-- alter table public."daily_events" alter column "priority" type character varying(10) using "priority"::character varying(10);
-- daily_events.created_at: A=timestamp without time zone  B=timestamp with time zone
-- alter table public."daily_events" alter column "created_at" type timestamp without time zone using "created_at"::timestamp without time zone;
-- daily_events.start_time: A=time without time zone  B=text
-- alter table public."daily_events" alter column "start_time" type time without time zone using "start_time"::time without time zone;
-- daily_events.start_time: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."daily_events" alter column "start_time" set not null;
-- daily_events.recurrence_rule: A=jsonb  B=text
-- alter table public."daily_events" alter column "recurrence_rule" type jsonb using "recurrence_rule"::jsonb;
-- habit_master.id: A=uuid  B=integer
-- alter table public."habit_master" alter column "id" type uuid using "id"::uuid;
-- habit_master.unit: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."habit_master" alter column "unit" set not null;
-- habit_master.created_at: A=timestamp without time zone  B=timestamp with time zone
-- alter table public."habit_master" alter column "created_at" type timestamp without time zone using "created_at"::timestamp without time zone;
-- travel_tasks.id: A=bigint  B=uuid
-- alter table public."travel_tasks" alter column "id" type bigint using "id"::bigint;
-- travel_tasks.category: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."travel_tasks" alter column "category" set not null;
-- travel_tasks.quadrant: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."travel_tasks" alter column "quadrant" set not null;
-- habit_entries.id: A=uuid  B=integer
-- alter table public."habit_entries" alter column "id" type uuid using "id"::uuid;
-- habit_entries.value: A=numeric(10,2)  B=numeric
-- alter table public."habit_entries" alter column "value" type numeric(10,2) using "value"::numeric(10,2);
-- habit_entries.value: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."habit_entries" alter column "value" set not null;
-- habit_entries.habit_id: A=uuid  B=integer
-- alter table public."habit_entries" alter column "habit_id" type uuid using "habit_id"::uuid;
-- project_tasks.status: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."project_tasks" alter column "status" set not null;
-- project_tasks.due_time: A=time without time zone  B=text
-- alter table public."project_tasks" alter column "due_time" type time without time zone using "due_time"::time without time zone;
-- project_tasks.priority: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."project_tasks" alter column "priority" set not null;
-- project_tasks.project_id: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."project_tasks" alter column "project_id" set not null;
-- project_tasks.start_time: A=time without time zone  B=text
-- alter table public."project_tasks" alter column "start_time" type time without time zone using "start_time"::time without time zone;
-- project_tasks.recurrence_interval: A=bigint  B=integer
-- alter table public."project_tasks" alter column "recurrence_interval" type bigint using "recurrence_interval"::bigint;
-- scribble_notes.content: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."scribble_notes" alter column "content" set not null;
-- task_overrides.task_id: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."task_overrides" alter column "task_id" set not null;
-- task_overrides.task_date: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."task_overrides" alter column "task_date" set not null;
-- vault_settings.password_hash: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."vault_settings" alter column "password_hash" set not null;
-- recurring_tasks.quadrant: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."recurring_tasks" alter column "quadrant" set not null;
-- recurring_tasks.task_text: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."recurring_tasks" alter column "task_text" set not null;
-- recurring_tasks.recurrence: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."recurring_tasks" alter column "recurrence" set not null;
-- recurring_tasks.start_date: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."recurring_tasks" alter column "start_date" set not null;
-- recurring_tasks.days_of_week: A=integer[]  B=jsonb
-- alter table public."recurring_tasks" alter column "days_of_week" type integer[] using "days_of_week"::integer[];
-- reference_links.url: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."reference_links" alter column "url" set not null;
-- reference_links.tags: A=text[]  B=jsonb
-- alter table public."reference_links" alter column "tags" type text[] using "tags"::text[];
-- project_subtasks.project_id: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."project_subtasks" alter column "project_id" set not null;
-- habit_goal_history.id: A=uuid  B=integer
-- alter table public."habit_goal_history" alter column "id" type uuid using "id"::uuid;
-- habit_goal_history.goal: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."habit_goal_history" alter column "goal" set not null;
-- habit_goal_history.habit_id: A=uuid  B=integer
-- alter table public."habit_goal_history" alter column "habit_id" type uuid using "habit_id"::uuid;
-- habit_goal_history.habit_id: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."habit_goal_history" alter column "habit_id" set not null;
-- habit_goal_history.effective_from: NOT NULL in A, nullable in B (fails if B has nulls):
-- alter table public."habit_goal_history" alter column "effective_from" set not null;
-- user_google_tokens.updated_at: A=timestamp without time zone  B=timestamp with time zone
-- alter table public."user_google_tokens" alter column "updated_at" type timestamp without time zone using "updated_at"::timestamp without time zone;

-- NOTES (no action generated)
-- tags.id: nullable in A but part of B's primary key — left NOT NULL
-- tags: RLS A=False B=True
-- epics: RLS A=False B=True
-- users: RLS A=False B=True
-- quotes: RLS A=False B=True
-- sprints: RLS A=False B=True
-- expenses: RLS A=False B=True
-- messages: RLS A=False B=True
-- projects: RLS A=False B=True
-- groceries: RLS A=False B=True
-- ref_cards: RLS A=False B=True
-- chat_rooms: RLS A=False B=True
-- daily_meta: RLS A=False B=True
-- kb_backlog: RLS A=False B=True
-- objectives: RLS A=False B=True
-- adhoc_tasks: RLS A=False B=True
-- daily_slots: columns only in B, left in place: priority_rank
-- daily_slots: RLS A=False B=True
-- inbox_links: RLS A=False B=True
-- initiatives: RLS A=False B=True
-- key_results: RLS A=False B=True
-- study_notes: RLS A=False B=True
-- todo_matrix: columns only in B, left in place: is_pinned, deleted_at, delegated_to, priority_rank
-- todo_matrix: RLS A=False B=True
-- daily_events: RLS A=False B=True
-- daily_health: columns only in B, left in place: goal
-- daily_health: RLS A=False B=True
-- family_tasks: RLS A=False B=True
-- habit_master: RLS A=False B=True
-- quick_bucket: RLS A=False B=True
-- ref_contexts: RLS A=False B=True
-- tasks_bucket: RLS A=False B=True
-- travel_reads: RLS A=False B=True
-- travel_tasks: columns only in B, left in place: position, deleted_at, is_deleted
-- travel_tasks: RLS A=False B=True
-- habit_entries: RLS A=False B=True
-- meeting_preps: RLS A=False B=True
-- project_tasks: columns only in B, left in place: updated_at, is_completed
-- project_tasks: RLS A=False B=True
-- relationships: RLS A=False B=True
-- scribble_notes: RLS A=False B=True
-- task_overrides: columns only in B, left in place: user_id, completed_date
-- task_overrides: RLS A=False B=True
-- task_time_logs: RLS A=False B=True
-- vault_settings: RLS A=False B=True
-- weekly_reviews: RLS A=False B=True
-- bedtime_stories: RLS A=False B=True
-- checklist_items: RLS A=False B=True
-- checklist_ticks: RLS A=False B=True
-- program_reviews: RLS A=False B=True
-- quote_favorites: RLS A=False B=True
-- recurring_tasks: RLS A=False B=True
-- reference_links: RLS A=False B=True
-- event_exceptions: RLS A=False B=True
-- project_subtasks: RLS A=False B=True
-- ref_activity_log: RLS A=False B=True
-- chat_room_members: RLS A=False B=True
-- mythology_stories: RLS A=False B=True
-- habit_goal_history: RLS A=False B=True
-- portfolio_holdings: RLS A=False B=True
-- push_subscriptions: RLS A=False B=True
-- tasks_bucket_stats: RLS A=False B=True
-- user_google_tokens: RLS A=False B=True
-- portfolio_snapshots: RLS A=False B=True
-- tasks_bucket_examples: RLS A=False B=True
-- checklist_reminder_log: RLS A=False B=True
-- portfolio_transactions: RLS A=False B=True
-- checklist_reminder_times: RLS A=False B=True
-- function rls_auto_enable() exists only in B (left in place)
